name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Use the secret you created in repository settings
          token: ${{ secrets.METRICS_TOKEN }}
          user: ankurbang
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: UTC
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 8
